github: awfixer # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: awfixer # Replace with a single Patreon username
ko_fi: awfixer # Replace with a single Ko-fi username
buy_me_a_coffee: awfixer # Replace with a single Buy Me a Coffee username
